// flow-typed signature: 8b59330d94f63e1a5a1a5e2318eae1fa
// flow-typed version: <<STUB>>/node-rest-client_v^2.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rest-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rest-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rest-client/lib/node-rest-client' {
  declare module.exports: any;
}

declare module 'node-rest-client/test/local-test' {
  declare module.exports: any;
}

declare module 'node-rest-client/test/specs' {
  declare module.exports: any;
}

declare module 'node-rest-client/test/test-proxy' {
  declare module.exports: any;
}

declare module 'node-rest-client/test/test-servers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rest-client/lib/node-rest-client.js' {
  declare module.exports: $Exports<'node-rest-client/lib/node-rest-client'>;
}
declare module 'node-rest-client/test/local-test.js' {
  declare module.exports: $Exports<'node-rest-client/test/local-test'>;
}
declare module 'node-rest-client/test/specs.js' {
  declare module.exports: $Exports<'node-rest-client/test/specs'>;
}
declare module 'node-rest-client/test/test-proxy.js' {
  declare module.exports: $Exports<'node-rest-client/test/test-proxy'>;
}
declare module 'node-rest-client/test/test-servers.js' {
  declare module.exports: $Exports<'node-rest-client/test/test-servers'>;
}
