// flow-typed signature: 0f9dbfb3e61e233ef4316eeb885693d6
// flow-typed version: <<STUB>>/palette-generator_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'palette-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'palette-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'palette-generator/lib/palette_generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'palette-generator/lib/palette_generator.js' {
  declare module.exports: $Exports<'palette-generator/lib/palette_generator'>;
}
