// flow-typed signature: 420e4f1084bed49c06e4c0ff8d9fa8f4
// flow-typed version: <<STUB>>/style-inject_v^0.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'style-inject/index' {
  declare module.exports: $Exports<'style-inject'>;
}
declare module 'style-inject/index.js' {
  declare module.exports: $Exports<'style-inject'>;
}
