// flow-typed signature: af37c00a6c23fc8063c18a2a72eddd5d
// flow-typed version: <<STUB>>/to-style_v^1.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-style/dist/index' {
  declare module.exports: any;
}

declare module 'to-style/dist/toStyle' {
  declare module.exports: any;
}

declare module 'to-style/hasOwn' {
  declare module.exports: any;
}

declare module 'to-style/prefixer' {
  declare module.exports: any;
}

declare module 'to-style/prefixInfo' {
  declare module.exports: any;
}

declare module 'to-style/src/cssPrefix' {
  declare module.exports: any;
}

declare module 'to-style/src/cssUnitless' {
  declare module.exports: any;
}

declare module 'to-style/src/hasOwn' {
  declare module.exports: any;
}

declare module 'to-style/src/isFunction' {
  declare module.exports: any;
}

declare module 'to-style/src/isObject' {
  declare module.exports: any;
}

declare module 'to-style/src/prefixer' {
  declare module.exports: any;
}

declare module 'to-style/src/prefixInfo' {
  declare module.exports: any;
}

declare module 'to-style/src/prefixProperties' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/camelize' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/hyphenate' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/hyphenRe' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/separate' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/toLowerFirst' {
  declare module.exports: any;
}

declare module 'to-style/src/stringUtils/toUpperFirst' {
  declare module.exports: any;
}

declare module 'to-style/src/stylePrefix' {
  declare module.exports: any;
}

declare module 'to-style/src/toStyleObject' {
  declare module.exports: any;
}

declare module 'to-style/src/toStyleString' {
  declare module.exports: any;
}

declare module 'to-style/test/toStyleObject' {
  declare module.exports: any;
}

declare module 'to-style/test/toStyleObjectCamelize' {
  declare module.exports: any;
}

declare module 'to-style/test/toStyleString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-style/dist/index.js' {
  declare module.exports: $Exports<'to-style/dist/index'>;
}
declare module 'to-style/dist/toStyle.js' {
  declare module.exports: $Exports<'to-style/dist/toStyle'>;
}
declare module 'to-style/hasOwn.js' {
  declare module.exports: $Exports<'to-style/hasOwn'>;
}
declare module 'to-style/index' {
  declare module.exports: $Exports<'to-style'>;
}
declare module 'to-style/index.js' {
  declare module.exports: $Exports<'to-style'>;
}
declare module 'to-style/prefixer.js' {
  declare module.exports: $Exports<'to-style/prefixer'>;
}
declare module 'to-style/prefixInfo.js' {
  declare module.exports: $Exports<'to-style/prefixInfo'>;
}
declare module 'to-style/src/cssPrefix.js' {
  declare module.exports: $Exports<'to-style/src/cssPrefix'>;
}
declare module 'to-style/src/cssUnitless.js' {
  declare module.exports: $Exports<'to-style/src/cssUnitless'>;
}
declare module 'to-style/src/hasOwn.js' {
  declare module.exports: $Exports<'to-style/src/hasOwn'>;
}
declare module 'to-style/src/isFunction.js' {
  declare module.exports: $Exports<'to-style/src/isFunction'>;
}
declare module 'to-style/src/isObject.js' {
  declare module.exports: $Exports<'to-style/src/isObject'>;
}
declare module 'to-style/src/prefixer.js' {
  declare module.exports: $Exports<'to-style/src/prefixer'>;
}
declare module 'to-style/src/prefixInfo.js' {
  declare module.exports: $Exports<'to-style/src/prefixInfo'>;
}
declare module 'to-style/src/prefixProperties.js' {
  declare module.exports: $Exports<'to-style/src/prefixProperties'>;
}
declare module 'to-style/src/stringUtils/camelize.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/camelize'>;
}
declare module 'to-style/src/stringUtils/hyphenate.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/hyphenate'>;
}
declare module 'to-style/src/stringUtils/hyphenRe.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/hyphenRe'>;
}
declare module 'to-style/src/stringUtils/separate.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/separate'>;
}
declare module 'to-style/src/stringUtils/toLowerFirst.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/toLowerFirst'>;
}
declare module 'to-style/src/stringUtils/toUpperFirst.js' {
  declare module.exports: $Exports<'to-style/src/stringUtils/toUpperFirst'>;
}
declare module 'to-style/src/stylePrefix.js' {
  declare module.exports: $Exports<'to-style/src/stylePrefix'>;
}
declare module 'to-style/src/toStyleObject.js' {
  declare module.exports: $Exports<'to-style/src/toStyleObject'>;
}
declare module 'to-style/src/toStyleString.js' {
  declare module.exports: $Exports<'to-style/src/toStyleString'>;
}
declare module 'to-style/test/toStyleObject.js' {
  declare module.exports: $Exports<'to-style/test/toStyleObject'>;
}
declare module 'to-style/test/toStyleObjectCamelize.js' {
  declare module.exports: $Exports<'to-style/test/toStyleObjectCamelize'>;
}
declare module 'to-style/test/toStyleString.js' {
  declare module.exports: $Exports<'to-style/test/toStyleString'>;
}
