// flow-typed signature: 1435d4f215ea8a3a75d93bf290293fe4
// flow-typed version: <<STUB>>/typescale_v0.0.8/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescale/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescale/lib/index.js' {
  declare module.exports: $Exports<'typescale/lib/index'>;
}
